/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSubjectsRouteImport } from './routes/admin.subjects'
import { Route as AdminIndicatorCategoriesRouteImport } from './routes/admin.indicator-categories'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIndicatorCategoriesRoute =
  AdminIndicatorCategoriesRouteImport.update({
    id: '/indicator-categories',
    path: '/indicator-categories',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/student': typeof StudentRoute
  '/teacher': typeof TeacherRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/indicator-categories': typeof AdminIndicatorCategoriesRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/student': typeof StudentRoute
  '/teacher': typeof TeacherRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/indicator-categories': typeof AdminIndicatorCategoriesRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/student': typeof StudentRoute
  '/teacher': typeof TeacherRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/indicator-categories': typeof AdminIndicatorCategoriesRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/admin/classes'
    | '/admin/indicator-categories'
    | '/admin/subjects'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/student'
    | '/teacher'
    | '/admin/classes'
    | '/admin/indicator-categories'
    | '/admin/subjects'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/admin/classes'
    | '/admin/indicator-categories'
    | '/admin/subjects'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  StudentRoute: typeof StudentRoute
  TeacherRoute: typeof TeacherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/indicator-categories': {
      id: '/admin/indicator-categories'
      path: '/indicator-categories'
      fullPath: '/admin/indicator-categories'
      preLoaderRoute: typeof AdminIndicatorCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClassesRoute: typeof AdminClassesRoute
  AdminIndicatorCategoriesRoute: typeof AdminIndicatorCategoriesRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClassesRoute: AdminClassesRoute,
  AdminIndicatorCategoriesRoute: AdminIndicatorCategoriesRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  StudentRoute: StudentRoute,
  TeacherRoute: TeacherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
